### PR TITLE
Handle terraform plan errors on deleted resources

### LINKED ISSUE #47: Workspace object hangs when terraform plan fails for destroy
### What happened?
The Workspace object is hung after delete was requested because the Observe is failing.  The terraform plan command fails because the AWS VPC object that the terraform is referencing has already been deleted:

```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2022-04-08T16:37:35Z
    Reason:                Deleting
    Status:                False
    Type:                  Ready
    Last Transition Time:  2022-04-08T16:38:06Z
    Message:               observe failed: cannot diff (i.e. plan) Terraform configuration: no matching ec2 vpc found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age                      From                                Message
  ----     ------                         ----                     ----                                -------
  Warning  CannotObserveExternalResource  3m17s (x4536 over 5d5h)  managed/workspace.tf.crossplane.io  cannot diff (i.e. plan) Terraform configuration: no matching ec2 vpc found
```

Removing the finalizer finishes the delete process on the Workspace but there needs to be a way to destroy the workspace when plan fails on destroy.

### How can we reproduce it?
Create a composition that creates a VPC.ec2.aws resource and references that resource in a Workspace, using data "aws_vpc".

When the claim gets deleted, if the VPC object is deleted from AWS before the Workspace delete executes, the problem occurs.

### What environment did it happen in?
Crossplane version: 1.7

* Cloud provider or hardware configuration AWS

### PR DESCRIPTION
**Pull request by bobh66**
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>

### Description of your changes
Update the Observe routine to check for deleted timestamp when terraform plan fails.  If the workspace depends on other resources that have already been deleted, the terraform plan will always fail and the workspace will never get deleted.

Fixes #47 

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
Added a unit test to cover the scenario and tested locally with Kind.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
What if the destroy failed for some other reason? It might create the illusion that associated cloud resources are removed when they are actually not. I am afraid we can create some cloud orphans introducing this change.

**Comment by bobh66** [comment]
I agree.  I'm going to investigate running tf.Destroy() again in this scenario - if that succeeds I think it's all we can reasonably do.

**Comment by bobh66** [comment]
@ytsarev - so running tf.Destroy() again in the Observe doesn't work - it returns the same error.  There are a couple of other possibilities:
-  if tf.Resources() returns nil then we should be guaranteed that there are no orphans left behind
- if tf,Destroy() is called with the "-refresh=false" argument, then in this scenario the delete completed successfully because the data elements were not refreshed, so they didn't notice that the VPC they referred to was gone.

There still scenarios that fail, for example when the Lease owner is an old pod that no longer exists, but that scenario can be dealt with separately.

I'll update the PR with this set of changes and we can discuss further.

Thanks

**Comment by bobh66** [comment]
Hi @ytsarev - the tf.Resources() function calls terraform state list and returns a list of the resources that are in the state file.   The list contains both actual "managed" resources that Terraform created, and any "data" items and "internal" resources like random numbers and time_sleep objects.   We can safely exclude the "data" entries and any of the internals, though identifying them all may be a challenge.

For example, in one of our "stuck" workspaces we have the following resources:

```
["data.aws_network_acls.vpc", "data.aws_vpc.vpc", "aws_default_network_acl.a", "aws_default_security_group.default", "aws_flow_log.fl", "time_sleep.wait_vpc"]
```

The only things that were "real" resources are the aws_default_network_acl, aws_default_security_group and aws_flow_log.  The first two were part of the VPC and were deleted when the VPC went away.  The flow log would be deleted by the Terraform destroy if it is run with -refresh=false.

I don't think there is any way to guarantee that resources won't be orphaned, but I think the best we can do is run Destroy normally, with -refresh=true, and if that fails run it again with -refresh=false.   If that succeeds then we're done, but if it fails I think manual intervention would be required to determine what the problem is.   At least until we can identify additional failure signatures.

I'm thinking this PR should be reworked to remove the checks from Observe() and update the Delete() code as described above, making a second call to Destroy() with the -refresh=false argument added to the list.

What do you think?

Thanks

**Comment by ytsarev** [comment]
@bobh66 before we implement that, I want to take a little step back and discuss the root cause scenario of #47.

Am I correct in understanding that we have a race condition between VPC Managed Resource and a Workspace Destroy when they are part of the same Composition? In other words, some form of resource ordering in regards to deletion would help here and the issue would be mitigated?

**Comment by bobh66** [comment]
@ytsarev - yes, exactly.   We have a composition that creates a VPC, and we need to use a Workspace to set up the security context of the VPC as those resources are not available in provider-aws.   Then when the delete happens, the VPC goes away before the Workspace and the result is that the Workspace is "stuck" in this condition.

I can see many cases where ordered deletion will be required to cleanly remove all resources.  We are also finding ways to write the Compositions so that there is an effective ordering of resource creation to resolve similar issues.

Any thoughts or suggestions in these areas are greatly appreciated.

Thanks

**Comment by bobh66** [comment]
Hi @ytsarev - what would you think about adding a "forProvider.destroyArgs" attribute that would allow the user to pass arguments to the tf.Destroy() method?  In this scenario we know that the resources "created" by the Terraform will not survive the deletion of the VPC, so running terraform destroy -refresh=false is perfectly safe.  This would give the author more control over the terraform command. since they presumably know what their terraform is doing.

We could add similar attributes for applyArgs, and planArgs for completeness, though at the moment I can't think of specific uses for them.

I think in general it will be difficult for the provider to determine what the Workspace is actually doing, so allowing the author more control over the underlying terraform commands is probably a good thing.

Thoughts?

Thanks!

**Comment by ytsarev** [comment]
@bobh66 that's actually a brilliant idea, I love it 👍

File: internal/controller/workspace/workspace.go [hunk 1]
```diff
@@ -252,8 +255,15 @@ func (c *external) Observe(ctx context.Context, mg resource.Managed) (managed.Ex
...
 	}
 
+	o = append(o, terraform.WithArgs(cr.Spec.ForProvider.PlanArgs))
 	differs, err := c.tf.Diff(ctx, o...)
 	if err != nil {
+		if meta.WasDeleted(mg) {
+			if derr := c.Delete(ctx, mg); derr != nil {
+				return managed.ExternalObservation{}, errors.Wrap(derr, errDiff)
+			}
+			return managed.ExternalObservation{ResourceExists: false}, nil
```
Comment (bobh66) [inline internal/controller/workspace/workspace.go:265]: @ytsarev - if we don't call Delete directly here, we need to return nil so the reconciler will call it later.   Otherwise it never gets called because of the Observe failure.  I think it's easier to read if we call it explicitly here, but it would get called later by the reconciler as long as we don't return an error when the resource is deleted.

Comment (ytsarev) [reply internal/controller/workspace/workspace.go:265]: @bobh66 do we still need to inject deletion into Observation after implementation of the custom arguments?

Comment (bobh66) [reply internal/controller/workspace/workspace.go:265]: @ytsarev Yes, the custom arguments can't keep the Observe from failing because it runs terraform plan, which does a refresh.  And since the Observe fails the Delete() function never gets called, so the custom argument to the Destroy command never gets invoked.   The only way to get to the Delete call when Observe fails is to call it within the Observe function.

**Review by ytsarev — CHANGES_REQUESTED** [review]
Please rebase with the master, otherwise looks great 👍

**Review by ytsarev — APPROVED** [review]
